services:
  # PostgreSQL Database
  service-crypto_postgres:
    image: postgres:17-alpine
    container_name: container-crypto_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./crypto_docker/postgres_setting/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network-crypto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PgAdmin Web UI
  service-crypto_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: container-crypto_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - network-crypto
    depends_on:
      service-crypto_postgres:
        condition: service_healthy

  # ETL Application
  service-crypto_etl:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: container-crypto_etl
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - network-crypto
    depends_on:
      service-crypto_postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  network-crypto:
    driver: bridge
